# Create a new image from the node:20-alpine image
FROM node:20-alpine

# Set the working directory in /app.
WORKDIR /app

# Copy the package.json file into the container.
COPY package.json /

# Install the dependencies.
RUN npm install

# Copy the rest of the application code into the container.
COPY . /

# Build the application.
RUN npm run build

# Expose the port 3000.
EXPOSE 3000

# Start the application.
CMD [ "npm", "start" ]